version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    command: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_HOST_AUTH_METHOD=trust

