version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    expose:
      - "6379"

  authRedis:
    image: redis:6.2-alpine
    command: --port 6380
    expose:
      - "6380"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    command: postgres
    expose:
      - "5432"
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/csvs:/var/lib/postgresql/csvs
      - ./ticket-data:/var/lib/postgresql/data

  authdb:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./auth-service/sql/auth.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./auth-data:/var/lib/postgresql/data
  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    expose:
      - "50052"
    depends_on:
      - authdb
      - authRedis
    links:
      - authdb
      - authRedis
  bank:
    build:
      context: ./bankService
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"

  ticket:
    build:
      context: ./ticketService
      dockerfile: Dockerfile
    expose:
      - "50050"
    depends_on:
      - postgres
      - bank
    links:
      - postgres
      - redis
      - bank

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "8081"
    depends_on:
      - postgres
      - ticket
      - bank
      - auth
    links:
      - postgres
      - bank
      - ticket
      - auth
  reverse-proxy:
    restart: always
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
        - "9000:80"
    depends_on:
      - postgres
      - ticket
      - bank
      - auth
    links:
      - postgres
      - bank
      - ticket
      - auth

networks:
  default:
    driver: bridge
    name: flightservice