version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    command: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/csvs:/var/lib/postgresql/csvs

  bank:
    build:
      context: ./bankService
      dockerfile: Dockerfile
    ports:
      - "8999:8080"
    depends_on:
      - postgres