version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    expose:
      - "6379"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    command: postgres
    expose:
      - "5432"
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/csvs:/var/lib/postgresql/csvs

  bank:
    build:
      context: ./bankService
      dockerfile: Dockerfile
    ports:
      - "8999:8080"

  ticket:
    build:
      context: ./ticketService
      dockerfile: Dockerfile
    expose:
      - "50050"
    depends_on:
      - postgres
      - bank
    links:
      - postgres
      - bank

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - ticket
      - bank
    links:
      - postgres
      - bank
      - ticket