version: '3.7'

services:
  db:
    image: postgres
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/auth.sql:/docker-entrypoint-initdb.d/create_tables.sql
