// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authorization

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupData_GENDER_TYPES int32

const (
	SignupData_MEN   SignupData_GENDER_TYPES = 0
	SignupData_WOMEN SignupData_GENDER_TYPES = 1
	SignupData_SO_SO SignupData_GENDER_TYPES = 2
)

var SignupData_GENDER_TYPES_name = map[int32]string{
	0: "MEN",
	1: "WOMEN",
	2: "SO_SO",
}

var SignupData_GENDER_TYPES_value = map[string]int32{
	"MEN":   0,
	"WOMEN": 1,
	"SO_SO": 2,
}

func (x SignupData_GENDER_TYPES) String() string {
	return proto.EnumName(SignupData_GENDER_TYPES_name, int32(x))
}

func (SignupData_GENDER_TYPES) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0, 0}
}

type SignupResponse_SIGNUP_STATUS int32

const (
	SignupResponse_DUPLICATE_EMAIL_OR_PHONE_NUMBER_403 SignupResponse_SIGNUP_STATUS = 0
	SignupResponse_FAILED_TO_HASH_PASSWORD_400         SignupResponse_SIGNUP_STATUS = 1
	SignupResponse_FAILED_TO_CREATE_USER_400           SignupResponse_SIGNUP_STATUS = 2
	SignupResponse_OK_201                              SignupResponse_SIGNUP_STATUS = 3
)

var SignupResponse_SIGNUP_STATUS_name = map[int32]string{
	0: "DUPLICATE_EMAIL_OR_PHONE_NUMBER_403",
	1: "FAILED_TO_HASH_PASSWORD_400",
	2: "FAILED_TO_CREATE_USER_400",
	3: "OK_201",
}

var SignupResponse_SIGNUP_STATUS_value = map[string]int32{
	"DUPLICATE_EMAIL_OR_PHONE_NUMBER_403": 0,
	"FAILED_TO_HASH_PASSWORD_400":         1,
	"FAILED_TO_CREATE_USER_400":           2,
	"OK_201":                              3,
}

func (x SignupResponse_SIGNUP_STATUS) String() string {
	return proto.EnumName(SignupResponse_SIGNUP_STATUS_name, int32(x))
}

func (SignupResponse_SIGNUP_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1, 0}
}

type SignInResponse_SINGIN_STATUS int32

const (
	SignInResponse_WRONG_EMAIL_OR_PHONE_NUMBER_OR_PASSWORD SignInResponse_SINGIN_STATUS = 0
	SignInResponse_OK_200                                  SignInResponse_SINGIN_STATUS = 1
)

var SignInResponse_SINGIN_STATUS_name = map[int32]string{
	0: "WRONG_EMAIL_OR_PHONE_NUMBER_OR_PASSWORD",
	1: "OK_200",
}

var SignInResponse_SINGIN_STATUS_value = map[string]int32{
	"WRONG_EMAIL_OR_PHONE_NUMBER_OR_PASSWORD": 0,
	"OK_200": 1,
}

func (x SignInResponse_SINGIN_STATUS) String() string {
	return proto.EnumName(SignInResponse_SINGIN_STATUS_name, int32(x))
}

func (SignInResponse_SINGIN_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3, 0}
}

type SignOutResponse_SIGN_OUT_STATUS int32

const (
	SignOutResponse_AUTHORIZATION_ERROR_401 SignOutResponse_SIGN_OUT_STATUS = 0
	SignOutResponse_FAILED_TO_SIGN_OUT      SignOutResponse_SIGN_OUT_STATUS = 1
	SignOutResponse_OK_201                  SignOutResponse_SIGN_OUT_STATUS = 2
)

var SignOutResponse_SIGN_OUT_STATUS_name = map[int32]string{
	0: "AUTHORIZATION_ERROR_401",
	1: "FAILED_TO_SIGN_OUT",
	2: "OK_201",
}

var SignOutResponse_SIGN_OUT_STATUS_value = map[string]int32{
	"AUTHORIZATION_ERROR_401": 0,
	"FAILED_TO_SIGN_OUT":      1,
	"OK_201":                  2,
}

func (x SignOutResponse_SIGN_OUT_STATUS) String() string {
	return proto.EnumName(SignOutResponse_SIGN_OUT_STATUS_name, int32(x))
}

func (SignOutResponse_SIGN_OUT_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5, 0}
}

type UserInfoResponse_USERINFO_STATUS int32

const (
	UserInfoResponse_AUTHORIZATION_ERROR_401 UserInfoResponse_USERINFO_STATUS = 0
	UserInfoResponse_FAILED_TO_SIGN_OUT      UserInfoResponse_USERINFO_STATUS = 1
	UserInfoResponse_OK_200                  UserInfoResponse_USERINFO_STATUS = 2
)

var UserInfoResponse_USERINFO_STATUS_name = map[int32]string{
	0: "AUTHORIZATION_ERROR_401",
	1: "FAILED_TO_SIGN_OUT",
	2: "OK_200",
}

var UserInfoResponse_USERINFO_STATUS_value = map[string]int32{
	"AUTHORIZATION_ERROR_401": 0,
	"FAILED_TO_SIGN_OUT":      1,
	"OK_200":                  2,
}

func (x UserInfoResponse_USERINFO_STATUS) String() string {
	return proto.EnumName(UserInfoResponse_USERINFO_STATUS_name, int32(x))
}

func (UserInfoResponse_USERINFO_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7, 0}
}

type SignupData struct {
	Email                string                  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string                  `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender               SignupData_GENDER_TYPES `protobuf:"varint,5,opt,name=gender,proto3,enum=authorization.SignupData_GENDER_TYPES" json:"gender,omitempty"`
	FirstName            string                  `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                  `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password             string                  `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SignupData) Reset()         { *m = SignupData{} }
func (m *SignupData) String() string { return proto.CompactTextString(m) }
func (*SignupData) ProtoMessage()    {}
func (*SignupData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *SignupData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupData.Unmarshal(m, b)
}
func (m *SignupData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupData.Marshal(b, m, deterministic)
}
func (m *SignupData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupData.Merge(m, src)
}
func (m *SignupData) XXX_Size() int {
	return xxx_messageInfo_SignupData.Size(m)
}
func (m *SignupData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupData.DiscardUnknown(m)
}

var xxx_messageInfo_SignupData proto.InternalMessageInfo

func (m *SignupData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupData) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SignupData) GetGender() SignupData_GENDER_TYPES {
	if m != nil {
		return m.Gender
	}
	return SignupData_MEN
}

func (m *SignupData) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignupData) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SignupData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupResponse struct {
	Status               SignupResponse_SIGNUP_STATUS `protobuf:"varint,7,opt,name=status,proto3,enum=authorization.SignupResponse_SIGNUP_STATUS" json:"status,omitempty"`
	UserId               int64                        `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetStatus() SignupResponse_SIGNUP_STATUS {
	if m != nil {
		return m.Status
	}
	return SignupResponse_DUPLICATE_EMAIL_OR_PHONE_NUMBER_403
}

func (m *SignupResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SignInData struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInData) Reset()         { *m = SignInData{} }
func (m *SignInData) String() string { return proto.CompactTextString(m) }
func (*SignInData) ProtoMessage()    {}
func (*SignInData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *SignInData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInData.Unmarshal(m, b)
}
func (m *SignInData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInData.Marshal(b, m, deterministic)
}
func (m *SignInData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInData.Merge(m, src)
}
func (m *SignInData) XXX_Size() int {
	return xxx_messageInfo_SignInData.Size(m)
}
func (m *SignInData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInData.DiscardUnknown(m)
}

var xxx_messageInfo_SignInData proto.InternalMessageInfo

func (m *SignInData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInData) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SignInData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	AccessToken          string                       `protobuf:"bytes,3,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string                       `protobuf:"bytes,4,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	Status               SignInResponse_SINGIN_STATUS `protobuf:"varint,7,opt,name=status,proto3,enum=authorization.SignInResponse_SINGIN_STATUS" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SignInResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *SignInResponse) GetStatus() SignInResponse_SINGIN_STATUS {
	if m != nil {
		return m.Status
	}
	return SignInResponse_WRONG_EMAIL_OR_PHONE_NUMBER_OR_PASSWORD
}

type SignOutData struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutData) Reset()         { *m = SignOutData{} }
func (m *SignOutData) String() string { return proto.CompactTextString(m) }
func (*SignOutData) ProtoMessage()    {}
func (*SignOutData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *SignOutData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutData.Unmarshal(m, b)
}
func (m *SignOutData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutData.Marshal(b, m, deterministic)
}
func (m *SignOutData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutData.Merge(m, src)
}
func (m *SignOutData) XXX_Size() int {
	return xxx_messageInfo_SignOutData.Size(m)
}
func (m *SignOutData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutData.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutData proto.InternalMessageInfo

func (m *SignOutData) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SignOutData) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type SignOutResponse struct {
	Status               SignOutResponse_SIGN_OUT_STATUS `protobuf:"varint,4,opt,name=status,proto3,enum=authorization.SignOutResponse_SIGN_OUT_STATUS" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *SignOutResponse) Reset()         { *m = SignOutResponse{} }
func (m *SignOutResponse) String() string { return proto.CompactTextString(m) }
func (*SignOutResponse) ProtoMessage()    {}
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *SignOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutResponse.Unmarshal(m, b)
}
func (m *SignOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutResponse.Marshal(b, m, deterministic)
}
func (m *SignOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutResponse.Merge(m, src)
}
func (m *SignOutResponse) XXX_Size() int {
	return xxx_messageInfo_SignOutResponse.Size(m)
}
func (m *SignOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutResponse proto.InternalMessageInfo

func (m *SignOutResponse) GetStatus() SignOutResponse_SIGN_OUT_STATUS {
	if m != nil {
		return m.Status
	}
	return SignOutResponse_AUTHORIZATION_ERROR_401
}

type UserInfoData struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoData) Reset()         { *m = UserInfoData{} }
func (m *UserInfoData) String() string { return proto.CompactTextString(m) }
func (*UserInfoData) ProtoMessage()    {}
func (*UserInfoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *UserInfoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoData.Unmarshal(m, b)
}
func (m *UserInfoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoData.Marshal(b, m, deterministic)
}
func (m *UserInfoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoData.Merge(m, src)
}
func (m *UserInfoData) XXX_Size() int {
	return xxx_messageInfo_UserInfoData.Size(m)
}
func (m *UserInfoData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoData.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoData proto.InternalMessageInfo

func (m *UserInfoData) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserInfoData) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type UserInfoResponse struct {
	User                 *UserData                        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Status               UserInfoResponse_USERINFO_STATUS `protobuf:"varint,9,opt,name=status,proto3,enum=authorization.UserInfoResponse_USERINFO_STATUS" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserInfoResponse) GetStatus() UserInfoResponse_USERINFO_STATUS {
	if m != nil {
		return m.Status
	}
	return UserInfoResponse_AUTHORIZATION_ERROR_401
}

type UserData struct {
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	FirstName            string   `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserData) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserData) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserData) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterEnum("authorization.SignupData_GENDER_TYPES", SignupData_GENDER_TYPES_name, SignupData_GENDER_TYPES_value)
	proto.RegisterEnum("authorization.SignupResponse_SIGNUP_STATUS", SignupResponse_SIGNUP_STATUS_name, SignupResponse_SIGNUP_STATUS_value)
	proto.RegisterEnum("authorization.SignInResponse_SINGIN_STATUS", SignInResponse_SINGIN_STATUS_name, SignInResponse_SINGIN_STATUS_value)
	proto.RegisterEnum("authorization.SignOutResponse_SIGN_OUT_STATUS", SignOutResponse_SIGN_OUT_STATUS_name, SignOutResponse_SIGN_OUT_STATUS_value)
	proto.RegisterEnum("authorization.UserInfoResponse_USERINFO_STATUS", UserInfoResponse_USERINFO_STATUS_name, UserInfoResponse_USERINFO_STATUS_value)
	proto.RegisterType((*SignupData)(nil), "authorization.SignupData")
	proto.RegisterType((*SignupResponse)(nil), "authorization.SignupResponse")
	proto.RegisterType((*SignInData)(nil), "authorization.SignInData")
	proto.RegisterType((*SignInResponse)(nil), "authorization.SignInResponse")
	proto.RegisterType((*SignOutData)(nil), "authorization.SignOutData")
	proto.RegisterType((*SignOutResponse)(nil), "authorization.SignOutResponse")
	proto.RegisterType((*UserInfoData)(nil), "authorization.UserInfoData")
	proto.RegisterType((*UserInfoResponse)(nil), "authorization.UserInfoResponse")
	proto.RegisterType((*UserData)(nil), "authorization.UserData")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4f, 0x4f, 0xdb, 0x48,
	0x14, 0xb7, 0x1d, 0xe2, 0x24, 0x2f, 0x21, 0x58, 0xa3, 0x15, 0x04, 0x22, 0x16, 0xd6, 0x2b, 0x2d,
	0x48, 0x68, 0xbd, 0x21, 0x70, 0x5e, 0xc9, 0x25, 0x26, 0x71, 0x0b, 0x76, 0x34, 0xb6, 0x85, 0xda,
	0xcb, 0xc8, 0xc0, 0x40, 0xa2, 0x12, 0x3b, 0xb2, 0x1d, 0x55, 0xea, 0xb9, 0xc7, 0xde, 0xfb, 0x29,
	0x7a, 0xe8, 0xf7, 0xe9, 0xb5, 0x1f, 0xa1, 0xf7, 0x6a, 0xc6, 0xf9, 0x8f, 0x09, 0x95, 0xda, 0x9b,
	0xe7, 0xfd, 0x7f, 0xbf, 0xf7, 0x7b, 0xcf, 0x00, 0xfe, 0x28, 0xe9, 0x69, 0xc3, 0x28, 0x4c, 0x42,
	0xb4, 0xce, 0xbe, 0xc3, 0xa8, 0xff, 0xde, 0x4f, 0xfa, 0x61, 0xa0, 0x7e, 0x94, 0x00, 0x9c, 0xfe,
	0x7d, 0x30, 0x1a, 0xb6, 0xfc, 0xc4, 0x47, 0x7f, 0x40, 0x9e, 0x0e, 0xfc, 0xfe, 0x43, 0x2d, 0xb7,
	0x2f, 0x1e, 0x96, 0x70, 0xfa, 0x40, 0x7f, 0x41, 0x65, 0xd8, 0x0b, 0x03, 0x4a, 0x82, 0xd1, 0xe0,
	0x9a, 0x46, 0xb5, 0x35, 0xae, 0x2c, 0x73, 0x99, 0xc5, 0x45, 0xe8, 0x7f, 0x90, 0xef, 0x69, 0x70,
	0x4b, 0xa3, 0x5a, 0x7e, 0x5f, 0x3c, 0xac, 0x36, 0xff, 0xd1, 0x16, 0xf2, 0x68, 0xb3, 0x1c, 0x5a,
	0xdb, 0xb0, 0x5a, 0x06, 0x26, 0xee, 0xeb, 0xae, 0xe1, 0xe0, 0xb1, 0x17, 0xda, 0x05, 0xb8, 0xeb,
	0x47, 0x71, 0x42, 0x02, 0x7f, 0x40, 0x6b, 0x32, 0x4f, 0x50, 0xe2, 0x12, 0xcb, 0x1f, 0x50, 0x54,
	0x87, 0xd2, 0x83, 0x3f, 0xd1, 0x16, 0xb8, 0xb6, 0xc8, 0x04, 0x5c, 0xb9, 0x03, 0xc5, 0xa1, 0x1f,
	0xc7, 0xef, 0xc2, 0xe8, 0xb6, 0x56, 0x4c, 0x75, 0x93, 0xb7, 0xfa, 0x2f, 0x54, 0xe6, 0xf3, 0xa1,
	0x02, 0xe4, 0x2e, 0x0d, 0x4b, 0x11, 0x50, 0x09, 0xf2, 0x57, 0x36, 0xfb, 0x14, 0xd9, 0xa7, 0x63,
	0x13, 0xc7, 0x56, 0x24, 0xf5, 0xbb, 0x08, 0xd5, 0xb4, 0x54, 0x4c, 0xe3, 0x61, 0x18, 0xc4, 0x14,
	0x9d, 0x81, 0x1c, 0x27, 0x7e, 0x32, 0x8a, 0x79, 0xde, 0x6a, 0xf3, 0x28, 0xb3, 0xb3, 0x89, 0xb9,
	0xe6, 0x98, 0x6d, 0xcb, 0xeb, 0x12, 0xc7, 0xd5, 0x5d, 0xcf, 0xc1, 0x63, 0x57, 0xb4, 0x05, 0x85,
	0x51, 0x4c, 0x23, 0xd2, 0x4f, 0x2b, 0xcc, 0x61, 0x99, 0x3d, 0xcd, 0x5b, 0xf5, 0x83, 0x08, 0xeb,
	0x0b, 0x2e, 0xe8, 0x00, 0xfe, 0x6e, 0x79, 0xdd, 0x0b, 0xf3, 0x4c, 0x77, 0x0d, 0x62, 0x5c, 0xea,
	0xe6, 0x05, 0xb1, 0x31, 0xe9, 0x76, 0x6c, 0xcb, 0x20, 0x96, 0x77, 0xf9, 0xc2, 0xc0, 0xe4, 0xb4,
	0x71, 0xa2, 0x08, 0x68, 0x0f, 0xea, 0xe7, 0xba, 0x79, 0x61, 0xb4, 0x88, 0x6b, 0x93, 0x8e, 0xee,
	0x74, 0x48, 0x57, 0x77, 0x9c, 0x2b, 0x1b, 0xb7, 0xc8, 0x69, 0xa3, 0xa1, 0x88, 0x68, 0x17, 0xb6,
	0x67, 0x06, 0x67, 0xd8, 0x60, 0x01, 0x3d, 0x87, 0xfb, 0x37, 0x14, 0x09, 0x01, 0xc8, 0xf6, 0x2b,
	0xd2, 0x6c, 0x1c, 0x2b, 0x39, 0xd5, 0x4f, 0x59, 0x60, 0x06, 0x8b, 0x2c, 0x10, 0x57, 0xb1, 0x40,
	0x7a, 0xcc, 0x82, 0xf9, 0x49, 0xe4, 0x96, 0x26, 0xf1, 0x6d, 0x0c, 0xad, 0x19, 0x4c, 0xa1, 0xdd,
	0x87, 0xb2, 0x7f, 0x73, 0x43, 0xe3, 0xd8, 0x0d, 0xdf, 0xd2, 0x60, 0xec, 0x31, 0x2f, 0x42, 0x2a,
	0x54, 0x22, 0x7a, 0x17, 0xd1, 0xb8, 0x97, 0x9a, 0xa4, 0xcc, 0x5b, 0x90, 0xfd, 0xd4, 0x80, 0x66,
	0x49, 0x35, 0xc7, 0xb4, 0xda, 0xa6, 0xb5, 0x34, 0x20, 0xb5, 0xc3, 0xc6, 0x30, 0xa7, 0x40, 0x47,
	0x70, 0x70, 0x85, 0x6d, 0xab, 0xfd, 0xc4, 0x08, 0xd8, 0x7b, 0x8c, 0xb6, 0x22, 0x4c, 0xa1, 0x6c,
	0x28, 0xa2, 0xea, 0x40, 0x99, 0x65, 0xb4, 0x47, 0x09, 0xc7, 0x72, 0xa9, 0x47, 0xf1, 0xf9, 0x1e,
	0xa5, 0xc7, 0x3d, 0xaa, 0x9f, 0x45, 0xd8, 0x18, 0x47, 0x9d, 0xa2, 0x77, 0x3e, 0xed, 0x7b, 0x8d,
	0xf7, 0xad, 0x65, 0xf4, 0x3d, 0x67, 0xcf, 0x99, 0x49, 0x6c, 0xcf, 0x5d, 0x6e, 0x1d, 0xc3, 0xc6,
	0x92, 0x0a, 0xd5, 0x61, 0x4b, 0xf7, 0xdc, 0x8e, 0x8d, 0xcd, 0x37, 0xba, 0x6b, 0xda, 0x16, 0x31,
	0x30, 0xb6, 0x19, 0x6f, 0x8e, 0x15, 0x01, 0x6d, 0x02, 0x9a, 0xd1, 0x6a, 0xe2, 0xa9, 0x88, 0x73,
	0x7c, 0x92, 0x54, 0x17, 0x2a, 0x1e, 0x23, 0x78, 0x70, 0x17, 0xfe, 0x46, 0x14, 0xbe, 0x8a, 0xa0,
	0x4c, 0xc2, 0x4e, 0x61, 0x38, 0x82, 0x35, 0xb6, 0x4b, 0xdc, 0xa1, 0xdc, 0xdc, 0x5a, 0x02, 0x81,
	0x99, 0xb3, 0x0a, 0x30, 0x37, 0x42, 0xed, 0x29, 0x66, 0x25, 0x8e, 0xd9, 0x7f, 0x19, 0xe6, 0xf3,
	0xd1, 0x35, 0xb6, 0x2f, 0xa6, 0x75, 0x6e, 0x67, 0x80, 0xb6, 0xa4, 0xfa, 0x35, 0xd0, 0x1a, 0x8a,
	0xa4, 0x7e, 0x12, 0xa1, 0x38, 0xa9, 0x77, 0xb6, 0x83, 0xd2, 0xaa, 0x1d, 0xcc, 0x3d, 0xde, 0xc1,
	0xcd, 0xe9, 0x25, 0x4e, 0x97, 0x25, 0xfb, 0xc2, 0xe6, 0x57, 0x5e, 0x58, 0x79, 0xf1, 0xc2, 0x36,
	0xbf, 0x48, 0x50, 0xd5, 0x47, 0x49, 0x8f, 0x06, 0x49, 0xff, 0x86, 0x23, 0x85, 0x5a, 0x20, 0xa7,
	0x97, 0x0f, 0x6d, 0x3f, 0x79, 0xea, 0x77, 0x76, 0x57, 0xde, 0x4a, 0x55, 0x98, 0x44, 0x31, 0x83,
	0xcc, 0x28, 0xe9, 0x39, 0xca, 0x8c, 0x32, 0x5b, 0x68, 0x55, 0x40, 0x6d, 0x28, 0x8c, 0xc9, 0x8e,
	0x76, 0xb2, 0x97, 0x80, 0xc7, 0xf9, 0x73, 0xf5, 0x82, 0xa8, 0x02, 0x7a, 0x99, 0x0e, 0x80, 0x31,
	0x00, 0xd5, 0x9f, 0xa0, 0x06, 0x0f, 0xb5, 0xf7, 0x0c, 0x6f, 0x54, 0xe1, 0x5a, 0xe6, 0xff, 0xdb,
	0x93, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x79, 0x1d, 0x16, 0x69, 0x7d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationClient interface {
	Signup(ctx context.Context, in *SignupData, opts ...grpc.CallOption) (*SignupResponse, error)
	SignIn(ctx context.Context, in *SignInData, opts ...grpc.CallOption) (*SignInResponse, error)
	SignOut(ctx context.Context, in *SignOutData, opts ...grpc.CallOption) (*SignOutResponse, error)
	UserInfo(ctx context.Context, in *UserInfoData, opts ...grpc.CallOption) (*UserInfoResponse, error)
}

type authenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationClient(cc grpc.ClientConnInterface) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) Signup(ctx context.Context, in *SignupData, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/authorization.Authentication/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) SignIn(ctx context.Context, in *SignInData, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/authorization.Authentication/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) SignOut(ctx context.Context, in *SignOutData, opts ...grpc.CallOption) (*SignOutResponse, error) {
	out := new(SignOutResponse)
	err := c.cc.Invoke(ctx, "/authorization.Authentication/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) UserInfo(ctx context.Context, in *UserInfoData, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/authorization.Authentication/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
type AuthenticationServer interface {
	Signup(context.Context, *SignupData) (*SignupResponse, error)
	SignIn(context.Context, *SignInData) (*SignInResponse, error)
	SignOut(context.Context, *SignOutData) (*SignOutResponse, error)
	UserInfo(context.Context, *UserInfoData) (*UserInfoResponse, error)
}

// UnimplementedAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (*UnimplementedAuthenticationServer) Signup(ctx context.Context, req *SignupData) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedAuthenticationServer) SignIn(ctx context.Context, req *SignInData) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthenticationServer) SignOut(ctx context.Context, req *SignOutData) (*SignOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (*UnimplementedAuthenticationServer) UserInfo(ctx context.Context, req *UserInfoData) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.Authentication/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Signup(ctx, req.(*SignupData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.Authentication/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).SignIn(ctx, req.(*SignInData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.Authentication/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).SignOut(ctx, req.(*SignOutData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.Authentication/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).UserInfo(ctx, req.(*UserInfoData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authorization.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Authentication_Signup_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _Authentication_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _Authentication_SignOut_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _Authentication_UserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
